# Generated by Django 4.2.16 on 2024-10-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phno", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
